SELECT customerid from(
SELECT CUSTOMER_ID as customerid, COUNT(CUSTOMER_ID) FROM ORDERS GROUP BY CUSTOMER_ID HAVING COUNT(CUSTOMER_ID)=(
SELECT MAX(COUNT(CUSTOMER_ID)) FROM ORDERS GROUP BY CUSTOMER_ID))A ORDER BY 1 ASC;




SELECT ID from(
SELECT ID,COUNT(ID) FROM CUS GROUP BY ID HAVING COUNT(ID)=(
SELECT max(Count(ID)) FROM CUS GROUP BY ID)order by 1 asc)A Where rownum=1;