SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/


WITH CTE AS 
(
SELECT
    GROUP_ID,
    PARTICIPANT_ID,
    PARTICIPANT_NAME,
    BET,
    'WINNER' AS RES
FROM
    EVENT_DETAILS
WHERE
    (GROUP_ID,
    SLICE_COUNT) IN (
    SELECT
        GROUP_Id ,
        MAX(CAST(SLICE_COUNT AS INTEGER))
    FROM
        EVENT_DETAILS
    GROUP BY
        GROUP_ID)
),
CTE2 AS 
(
SELECT GROUP_ID , SUM(BET2) AS BET3
FROM (
SELECT
    GROUP_ID,
    ROUND(BET * 0.3) AS BET2,
    'LOSER' AS RES
FROM
    EVENT_DETAILS
WHERE
    (GROUP_ID,
    SLICE_COUNT) NOT IN (
    SELECT
        GROUP_Id ,
        MAX(CAST(SLICE_COUNT AS INTEGER))
    FROM
        EVENT_DETAILS
    GROUP BY
        GROUP_ID)
) A
GROUP BY GROUP_ID 
        )
SELECT
    CTE.PARTICIPANT_NAME AS WINNER ,
    CTE.BET + CTE2.BET3 AS total_cast
FROM
    CTE
INNER JOIN CTE2
ON
    CTE.GROUP_ID = CTE2.GROUP_ID
    ORDER BY 1;

exit;